name: "build-image: platform=k8s, survey=ztf, science=true"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  k8s-ztf-science:
    uses: ./.github/workflows/build-image-template.yml
    with:
      target: k8s
      survey: ztf
      suffix: science
      artifact_name: k8s-ztf-science
      ciux_suffix: science-ztf
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_token: ${{ secrets.REGISTRY_TOKEN }}